const completionSchem = {
  type: "object",
  properties: {
    model: {
      type: "string",
      enum: [
        "text-davinci-003",
        "text-davinci-002",
        "text-curie-001",
        "text-babbage-001",
        "text-ada-001",
        "davinci",
        "curie",
        "babbage",
        "ada",
      ],
    },
    prompt: { type: ["string", "array"], default: "" },
    suffix: { type: "string", default: null },
    max_tokens: { type: "integer", default: 16 },
    temperature: { type: "number", default: 1, minimum: 0, maximum: 2 },
    top_p: { type: "number", minimum: 0, default: 1, maximum: 1 },
    n: { type: "integer", default: 1 },
    stream: { type: "boolean", default: false },
    logprobs: { type: "integer", default: null },
    echo: { type: "boolean", default: false },
    stop: { type: "string", default: null },
    presence_penalty: { type: "number", default: 0, minimum: -2, maximum: 2 },
    frequency_penalty: { type: "number", default: 0, minimum: -2, maximum: 2 },
    best_of: { type: "number", default: 1, minimum: -2, maximum: 2 },
    logit_bias: { default: null },
    user: { type: "string" },
  },
  required: ["model"],
};
